In [6]:
import pandas as pd 
import numpy as nb
import seaborn as sns

In [ ]:
df = pd.read_csv('apartments_rent_pl_2024_01.csv')
df.head(5)

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,pharmacyDistance,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price
0,2a1a6db97ff122d6bc148abb6f0e498a,szczecin,blockOfFlats,52.0,2.0,3.0,3.0,2008.0,53.460535,14.545416,...,0.307,condominium,brick,NaN,yes,yes,no,no,no,3500
1,368e16142922433c709e6921a3b8f2a8,szczecin,blockOfFlats,70.0,3.0,7.0,11.0,1985.0,53.378485,14.657089,...,0.086,condominium,concreteSlab,premium,no,yes,yes,no,no,2900
2,655acd54eb518a718fd1f59fd7161c61,szczecin,blockOfFlats,43.0,2.0,3.0,3.0,1960.0,53.425946,14.559489,...,0.338,condominium,concreteSlab,premium,no,yes,no,no,yes,2900
3,99f85bbc55d110aa5a79ad4c7d5a0562,szczecin,blockOfFlats,46.7,2.0,1.0,4.0,1980.0,53.446990,14.556851,...,0.096,condominium,concreteSlab,premium,no,no,no,no,yes,2400
4,601b83a79fb6b89fe8e488bfcdd5e872,szczecin,NaN,56.2,3.0,1.0,4.0,NaN,53.441100,14.549100,...,0.050,condominium,NaN,NaN,no,no,NaN,no,no,3000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8430 entries, 0 to 8429
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    8430 non-null   object
 1   city                  8430 non-null   object
 2   type                  6227 non-null   object
 3   squareMeters          8430 non-null   float64
 4   rooms                 8430 non-null   float64
 5   floor                 7400 non-null   float64
 6   floorCount            8259 non-null   float64
 7   buildYear             5938 non-null   float64
 8   latitude              8430 non-null   float64
 9   longitude             8430 non-null   float64
 10  centreDistance        8430 non-null   float64
 11  poiCount              8430 non-null   float64
 12  schoolDistance        8428 non-null   float64
 13  clinicDistance        8425 non-null   float64
 14  postOfficeDistance    8425 non-null   float64
 15  kindergartenDistance  8423 non-null   float64
 16  restaurantDistance    8406 non-null   float64
 17  collegeDistance       8326 non-null   float64
 18  pharmacyDistance      8417 non-null   float64
 19  ownership             8430 non-null   object
 20  buildingMaterial      4971 non-null   object
 21  condition             2207 non-null   object
 22  hasParkingSpace       8430 non-null   object
 23  hasBalcony            8430 non-null   object
 24  hasElevator           7976 non-null   object
 25  hasSecurity           8430 non-null   object
 26  hasStorageRoom        8430 non-null   object
 27  price                 8430 non-null   int64
dtypes: float64(16), int64(1), object(11)
memory usage: 1.8+ MB

np.int64(0)

In [ ]:
#Usuwamy duplikaty z danych, których wsm nie było, ale używamy funkcji w razie czego
df.drop_duplicates()

,id,city,type,squareMeters,rooms,floor,floorCount,buildYear,latitude,longitude,...,pharmacyDistance,ownership,buildingMaterial,condition,hasParkingSpace,hasBalcony,hasElevator,hasSecurity,hasStorageRoom,price
0,2a1a6db97ff122d6bc148abb6f0e498a,szczecin,blockOfFlats,52.0,2.0,3.0,3.0,2008.0,53.460535,14.545416,...,0.307,condominium,brick,NaN,yes,yes,no,no,no,3500
1,368e16142922433c709e6921a3b8f2a8,szczecin,blockOfFlats,70.0,3.0,7.0,11.0,1985.0,53.378485,14.657089,...,0.086,condominium,concreteSlab,premium,no,yes,yes,no,no,2900
2,655acd54eb518a718fd1f59fd7161c61,szczecin,blockOfFlats,43.0,2.0,3.0,3.0,1960.0,53.425946,14.559489,...,0.338,condominium,concreteSlab,premium,no,yes,no,no,yes,2900
3,99f85bbc55d110aa5a79ad4c7d5a0562,szczecin,blockOfFlats,46.7,2.0,1.0,4.0,1980.0,53.446990,14.556851,...,0.096,condominium,concreteSlab,premium,no,no,no,no,yes,2400
4,601b83a79fb6b89fe8e488bfcdd5e872,szczecin,NaN,56.2,3.0,1.0,4.0,NaN,53.441100,14.549100,...,0.050,condominium,NaN,NaN,no,no,NaN,no,no,3000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8425,aeb9ea42eecfe32b2f791efe372a2e76,bydgoszcz,tenement,45.0,2.0,1.0,1.0,NaN,53.129551,18.029431,...,0.024,condominium,brick,NaN,no,no,NaN,no,no,2500
8426,4018cc5a9fd48bb2d66b84bc5e1b46ab,bydgoszcz,tenement,55.0,3.0,2.0,2.0,NaN,53.129551,18.029431,...,0.024,condominium,brick,NaN,no,no,no,no,no,3200
8427,89fdf9ecda6fe6aa95e34528fa82f55f,bydgoszcz,blockOfFlats,48.0,2.0,3.0,3.0,2019.0,53.121200,17.992500,...,0.300,condominium,brick,NaN,no,no,no,no,no,2700
8428,095b187d0bbce092d4b03164e89710c5,bydgoszcz,blockOfFlats,50.0,2.0,1.0,3.0,2019.0,53.121200,17.992500,...,0.300,condominium,brick,NaN,no,yes,no,no,no,2800
8429,eee39c309b4f55e057485d848bb2772b,bydgoszcz,NaN,40.0,2.0,1.0,1.0,NaN,53.126000,18.007900,...,0.205,condominium,NaN,NaN,no,no,NaN,no,no,1500

In [11]:
#Sprawdzamy brak idanych
df.isna().sum()

id                         0
city                       0
type                    2203
squareMeters               0
rooms                      0
floor                   1030
floorCount               171
buildYear               2492
latitude                   0
longitude                  0
centreDistance             0
poiCount                   0
schoolDistance             2
clinicDistance             5
postOfficeDistance         5
kindergartenDistance       7
restaurantDistance        24
collegeDistance          104
pharmacyDistance          13
ownership                  0
buildingMaterial        3459
condition               6223
hasParkingSpace            0
hasBalcony                 0
hasElevator              454
hasSecurity                0
hasStorageRoom             0
price                      0
dtype: int64